import { resolve } from "node:path";
import { defineConfig, type UserManifest } from "wxt";
import tailwindcss from "@tailwindcss/vite";
import {
  PROMPT_FONT_PATH,
  PROMPT_FONT_SOURCE,
} from "./src/constants/prompt-font";
import { manifestCommands } from "./src/constants/shortcuts";

// See https://wxt.dev/api/config.html
export default defineConfig({
  modules: ["@wxt-dev/module-react"],
  srcDir: "src",
  zip: {
    // Store screenshots and artwork play no part in the build, so they stay
    // out of the sources zip that AMO reviews with every release.
    excludeSources: ["docs/store/**"],
  },
  hooks: {
    // The capture prompt's font, copied from the package rather than kept in
    // public/, so it always matches the installed version; see prompt-font.ts.
    "build:publicAssets": (_, assets) => {
      assets.push({
        absoluteSrc: resolve(PROMPT_FONT_SOURCE),
        relativeDest: PROMPT_FONT_PATH,
      });
    },
  },
  vite: () => ({
    plugins: [tailwindcss()],
    resolve: { alias: { "tailwind-merge": "cn", clsx: "cn" } }, //* cn is faster, but if this causes issues, then remove.
  }),
  // vite: () => ({
  //   plugins: [
  //     {
  //       name: "remove-zod-eval",
  //       transform(code: string, id: string) {
  //         if (id.includes("zod")) {
  //           return code.replace(
  //             /new Function\(""\)/g,
  //             '(() => { throw new Error("eval not allowed") })()',
  //           );
  //         }
  //       },
  //     },
  //   ],
  //   resolve: {
  //     dedupe: ["react", "react-dom"],
  //   },
  // }),
  manifest: ({ browser }) => {
    const manifestBase: UserManifest = {
      // Not package.json's name, which npm needs lowercase and hyphenated.
      name: "Lexicora",
      // No `description` or `version`: WXT takes both from package.json. The
      // description is the Chrome Web Store's summary, so at most 132
      // characters; the version names the zips too.
      permissions: [
        "storage",
        //* The library is the only copy, on this device: without this the
        //* browser may evict the database when the disk runs low. No install
        //* warning in Chrome; persistent IndexedDB in Firefox.
        "unlimitedStorage",
        "tabs",
        "activeTab",
        "scripting",
        "contextMenus",
        "clipboardWrite",
        //* NOTE: "sidePanel" is Chromium-only and is appended below; Firefox gets
        //* a `sidebar_action` key generated by WXT from the sidepanel entrypoint.
        ...(browser === "firefox" ? [] : (["sidePanel"] as const)),
      ],
      //host_permissions: ["<all_urls>"], //* NOTE: Not needed, activeTab should be enough
      // Browser-wide keyboard shortcuts — see src/constants/shortcuts.ts
      commands: manifestCommands(browser),
      //* The capture prompt reads its font file itself, rather than through a
      //* stylesheet a page's font-src policy can refuse; see prompt-font.ts.
      //* Reachable from the pages the content script runs on, and no others.
      web_accessible_resources: [
        {
          resources: [PROMPT_FONT_PATH],
          matches: ["http://*/*", "https://*/*", "file:///*"],
        },
      ],
    };

    let userManifest: UserManifest = manifestBase;

    // Firefox-specific settings
    if (browser === "firefox") {
      userManifest = {
        ...manifestBase,
        browser_specific_settings: {
          gecko: {
            id: "{d7fed14a-3919-4383-892e-dcc1a7b53988}",
            //* Required by AMO for new extensions from 2025-11-03. Lexicora stores
            //* everything locally and transmits nothing, so no data is collected.
            data_collection_permissions: {
              required: ["none"],
            },
          },
        },
      };
    }

    return userManifest;
  },
});
