import { defineConfig, type UserManifest } from "wxt";
import tailwindcss from "@tailwindcss/vite";

// See https://wxt.dev/api/config.html
export default defineConfig({
  modules: ["@wxt-dev/module-react"],
  srcDir: "src",
  vite: () => ({
    plugins: [tailwindcss()],
  }),
  // vite: () => ({
  //   plugins: [
  //     {
  //       name: "remove-zod-eval",
  //       transform(code: string, id: string) {
  //         if (id.includes("zod")) {
  //           return code.replace(
  //             /new Function\(""\)/g,
  //             '(() => { throw new Error("eval not allowed") })()',
  //           );
  //         }
  //       },
  //     },
  //   ],
  //   resolve: {
  //     dedupe: ["react", "react-dom"],
  //   },
  // }),
  manifest: ({ browser, manifestVersion, mode, command }) => {
    const manifestBase: UserManifest = {
      name: "Lexicora",
      description:
        "The Lexicora browser extension for capturing and organizing web content.",
      //"A browser extension for the Lexicora platform and services.",
      version: "0.1.0",
      permissions: [
        "storage",
        "tabs",
        "activeTab",
        "scripting",
        "contextMenus",
        "clipboardWrite",
        //* NOTE: "sidePanel" is Chromium-only and is appended below; Firefox gets
        //* a `sidebar_action` key generated by WXT from the sidepanel entrypoint.
        ...(browser === "firefox" ? [] : (["sidePanel"] as const)),
      ],
      //host_permissions: ["<all_urls>"], //* NOTE: Not needed, activeTab should be enough
    };

    let userManifest: UserManifest = manifestBase;

    // Firefox-specific settings
    if (browser === "firefox") {
      userManifest = {
        ...manifestBase,
        browser_specific_settings: {
          gecko: {
            id: "{d7fed14a-3919-4383-892e-dcc1a7b53988}",
            //* Required by AMO for new extensions from 2025-11-03. Lexicora stores
            //* everything locally and transmits nothing, so no data is collected.
            data_collection_permissions: {
              required: ["none"],
            },
          },
        },
      };
    }

    return userManifest;
  },
});
